from setuptools import find_packages, setup

setup(
    name='telescope-web',
    version='0.0.0',
    description='Web app demonstrating Telescope ML tool',
    author='Philip Vitale',
    license='MIT',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'Click',
        'cycler',
        'decorator',
        'Flask',
        'imageio',
        'itsdangerous',
        'Jinja2',
        'kiwisolver',
        'MarkupSafe',
        'matplotlib',
        'networkx',
        'numpy',
        'Pillow',
        'pyparsing',
        'pypng',
        'python-dateutil',
        'PyWavelets',
        'scikit-image',
        'scipy',
        'six',
        'torch',
        'torchvision',
        'Werkzeug',
    ],
)
